import type { NextPage } from 'next';
import Head from 'next/head';
import { Card, Slideshow } from '../components';
import { data } from '../data';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Piotr Ostrowski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <br />
        <div className="flex flex-col content-center items-center">
          <h1 className="text-2xl">Piotr Ostrowski</h1>
          <div>
            <div className="text-blue">
              <a href="https://piotr-ostrowski.s3.us-east-2.amazonaws.com/CV.pdf">
                Resume
              </a>
              {'  '}-{'  '}
              <a href="https://github.com/piotrostr/">Github</a>
              {'  '}-{'  '}
              <a href="https://piotr-ostrowski.s3.us-east-2.amazonaws.com/Most%20Recent%20Jobs.pdf">
                Recent Jobs
              </a>
            </div>
          </div>
        </div>
        <Slideshow>
          <a href="https://smplverse.xyz">
            <Card {...data.smplverse} />
          </a>
          <a href="https://health-token.com">
            <Card {...data.healthToken} />
          </a>
          <a href="https://pixilartillery.io">
            <Card {...data.pixilArtillery} />
          </a>
          <a href="https://stoned-cookies.vercel.app">
            <Card {...data.stonedCookies} />
          </a>
          <a href="https://domi-owczarek.biz">
            <Card {...data.domi} />
          </a>
          <a href="https://okemonos.com">
            <Card {...data.okemonos} />
          </a>
          <a href="https://www.luifs.com">
            <Card {...data.luifs} />
          </a>
        </Slideshow>
      </main>
      <footer>
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            flexDirection: 'column',
          }}
        >
          <a
            className="text-blue hover:no-underline"
            href="https://etherscan.io/address/0x2ed29d982b0120d49899a7cc7afe7f5d5435bc97"
          >
            <span>{'♡'}</span>
          </a>
        </div>
      </footer>
    </div>
  );
};

export default Home;
