import type { NextPage } from 'next';
import Head from 'next/head';
import { Card, Slideshow } from '../components';
import { nfts, websites, favourites } from '../data';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Piotr Ostrowski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="p-3 md:p-8 lg:p-12">
        <script defer></script>
        <div className="lg:flex lg:flex-row lg:space-x-5">
          <header className="h-screen sm:h-full">
            <div className="flex flex-col p-5 md:w-full lg:w-max">
              <div className="flex flex-col md:flex-row md:justify-between md:items-center lg:flex-col lg:justify-start lg:items-start">
                <h1 className="text-4xl mt-5">Piotr Ostrowski</h1>
                <div className="flex flex-row space-x-3 mt-3 md:mt-1 lg:mt-3">
                  <a href="https://github.com/piotrostr/">
                    <img
                      src="https://www.svgrepo.com/show/341847/github.svg"
                      width="30"
                      height="30"
                      alt="gh"
                    />
                  </a>
                  <a href="https://www.linkedin.com/in/piotr-ostrowski-3979261a3">
                    <img
                      src="https://www.svgrepo.com/show/103404/linkedin-logo.svg"
                      width="30"
                      height="30"
                      alt="linkedin"
                    />
                  </a>
                  <a href="https://medium.com/@piotr.ostrowski">
                    <img
                      src="https://cdn-icons-png.flaticon.com/512/5968/5968885.png"
                      width="30"
                      height="30"
                      alt="medium"
                    />
                  </a>
                  <a href="https://stackoverflow.com/users/14422054/piotr-ostrowski">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      version="1.1"
                      id="Layer_1"
                      x="0px"
                      y="0px"
                      viewBox="0 0 512 512"
                      width="30"
                      height="30"
                    >
                      <g id="XMLID_1_">
                        <path
                          id="XMLID_8_"
                          d="M512,320.2V512H0V320.2h64.2v128.5h384.5V320.2H512z M95.9,351.9h320.2v64.2H95.9V351.9z M103.3,283l14-62.4   l312.8,68.9l-14,62.4L103.3,283z M139.6,154.5l27-57.7l290.4,135l-27,57.7L139.6,154.5z M496.2,180.6l-39.1,51.2L202.9,36.3   L230.9,0h28.9L496.2,180.6z"
                        />
                      </g>
                    </svg>
                  </a>
                </div>
              </div>
              <p className="text-lg my-10 max-w-sm">
                Aspiring full stack developer passionate about AI and
                blockchain.
              </p>
              <div className="text-blue flex flex-col">
                <a
                  href="https://piotr-ostrowski.s3.us-east-2.amazonaws.com/Piotr%20Ostrowski%2C%20Resume.pdf"
                  className="hover:underline"
                >
                  Resume
                </a>
              </div>
            </div>
            <div className="p-5 md:p-8 my-12 w-full text-justify italic border-l-2 border-black ml-8 text-md max-w-xs md:max-w-md">
              <div>Hi there!</div>
              <br />
              <div className="mt-2">
                In case you would need to contact me please find my details in
                the resume above, otherwise feel free to scroll down through
                some of my projects!
              </div>
              <div className="mt-2">
                Everything here is available under MIT license (including this
                website), feel free to check out the code on my github.
              </div>
              <br />
              <div className="mt-2">Best,</div>
              <div>Piotr</div>
            </div>
          </header>
          <main>
            <div className="md: ml-5">
              <h2 className="m-3 text-lg">Personal Favourites</h2>
              <Slideshow>
                <a href="https://medium.com/@piotr.jp.ostrowski/run-tensorrt-in-10-bash-commands-b89a207d61c5">
                  <Card {...favourites.accelerate} />
                </a>
                <a href="https://smplverse.xyz">
                  <Card {...favourites.smplverse} />
                </a>
                <a href="https://health-token.com">
                  <Card {...favourites.healthToken} />
                </a>
              </Slideshow>
              <h2 className="m-3 text-lg">Websites</h2>
              <Slideshow>
                <a href="https://domi-owczarek.biz">
                  <Card {...websites.domi} />
                </a>
                <a href="https://www.luifs.com">
                  <Card {...websites.luifs} />
                </a>
                <a href="https://www.premiere.sh">
                  <Card {...websites.premiere} />
                </a>
              </Slideshow>
              <h2 className="m-3 text-lg">NFT Collections</h2>
              <Slideshow>
                <a href="https://stoned-cookies.vercel.app">
                  <Card {...nfts.stonedCookies} />
                </a>
                <a href="https://okemonos.com">
                  <Card {...nfts.okemonos} />
                </a>
                <a href="https://opensea.io/collection/skelftees-v2">
                  <Card {...nfts.skelftees} />
                </a>
              </Slideshow>
            </div>
          </main>
        </div>
        <footer className="p-8">
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              flexDirection: 'column',
            }}
          >
            <a
              className="text-blue hover:no-underline"
              href="https://etherscan.io/address/0x2ed29d982b0120d49899a7cc7afe7f5d5435bc97"
            >
              <span>{'♡'}</span>
            </a>
          </div>
        </footer>
      </body>
    </>
  );
};

export default Home;
